let dt = new Date(2022, 11, 4, 20, 7, 15, 368);
console.log(dt);
console.log(dt.getFullYear());
console.log(dt.getMonth());
console.log(dt.getDate());
console.log(dt.getDay());
console.log(dt.getHours());
console.log(dt.getMinutes());
console.log(dt.getSeconds());
console.log(dt.getMilliseconds());
console.log(dt.getTime());
console.log(dt.getTimezoneOffset());